url: "https://zero-divisor.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "dltc_homepage" # the subpath of your site, e.g. /blog
title: "Dark Legion Tabletop Club e.V." # the name of your site, e.g. ACME Corp.
